@TrackCubed.Api_HostAddress = http://localhost:5231

POST {{TrackCubed.Api_HostAddress}}/api/user/onboard
Accept: application/json

###

GET {{TrackCubed.Api_HostAddress}}/api/ItemTypes
Accept: application/json

###
